// 
// Decompiled by Procyon v0.5.36
// 

package net.minecraft.item.crafting;

import java.util.Arrays;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.block.BlockPrismarine;
import net.minecraft.block.BlockDirt;
import net.minecraft.block.BlockStoneBrick;
import net.minecraft.block.BlockStone;
import net.minecraft.block.BlockQuartz;
import net.minecraft.block.BlockStoneSlabNew;
import net.minecraft.block.BlockStoneSlab;
import net.minecraft.block.BlockRedSandstone;
import net.minecraft.block.BlockSandStone;
import net.minecraft.block.BlockSand;
import net.minecraft.init.Items;
import net.minecraft.block.Block;
import net.minecraft.item.ItemStack;
import net.minecraft.init.Blocks;
import java.security.Key;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

public class RecipesCrafting
{
    private static final /* synthetic */ String[] llllllIIIIIIl;
    private static final /* synthetic */ int[] llllllIlIlllI;
    
    private static void lIlIlllllIlIIlI() {
        (llllllIIIIIIl = new String[RecipesCrafting.llllllIlIlllI[75]])[RecipesCrafting.llllllIlIlllI[1]] = lIlIlllllIIIIll("W0lz", "xjPmc");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[2]] = lIlIlllllIIIlII("fxBmWo6C1B8=", "HHocz");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[3]] = lIlIlllllIIIIll("c3NZ", "PPzLK");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[4]] = lIlIlllllIIIIll("TH0=", "oPMEq");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[6]] = lIlIlllllIIIlIl("6QK8qaUJDpI=", "tzrOK");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[0]] = lIlIlllllIIIIll("eR1V", "ZXvOr");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[9]] = lIlIlllllIIIlII("LRrGQX82BAQ=", "MnRSg");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[8]] = lIlIlllllIIIlII("wkFkKxqnfy4=", "RrJtB");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[11]] = lIlIlllllIIIlII("y4tNvh9ehwM=", "ICAdl");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[12]] = lIlIlllllIIIlIl("JL7GFymdYLs=", "XILSZ");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[13]] = lIlIlllllIIIIll("cEk=", "SjVge");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[14]] = lIlIlllllIIIlII("qlOhKBHcA9U=", "MrHMj");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[15]] = lIlIlllllIIIlIl("yGNtNmSnLsQ=", "zkMXA");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[16]] = lIlIlllllIIIlII("EZSikp6J/6s=", "TYFVi");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[17]] = lIlIlllllIIIIll("S3I=", "hQIQi");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[18]] = lIlIlllllIIIIll("aHA=", "KSchF");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[19]] = lIlIlllllIIIlII("2DPlnZpXL2M=", "vTyox");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[20]] = lIlIlllllIIIlII("VT4LdFDZ0Sc=", "bJOQO");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[21]] = lIlIlllllIIIlII("ZJHv4VvSKUY=", "sVlWP");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[22]] = lIlIlllllIIIlIl("M20mj4dHHX8=", "IcGZw");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[23]] = lIlIlllllIIIIll("UA==", "szoJV");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[24]] = lIlIlllllIIIlIl("VFztla9Mc4Q=", "iNFCB");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[25]] = lIlIlllllIIIIll("ZQ==", "FChlw");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[26]] = lIlIlllllIIIIll("Uw==", "ppmVQ");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[27]] = lIlIlllllIIIIll("SQ==", "jfiLx");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[28]] = lIlIlllllIIIlII("ayrJzP61zak=", "inHiZ");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[29]] = lIlIlllllIIIlIl("tzvsZQUSlko=", "NYeyB");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[30]] = lIlIlllllIIIlIl("VtD45skwqdE=", "RznYI");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[31]] = lIlIlllllIIIIll("WnA=", "ySBDl");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[32]] = lIlIlllllIIIlIl("+kOtrTbzqGQ=", "UoZef");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[33]] = lIlIlllllIIIIll("Tg==", "mJtUT");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[34]] = lIlIlllllIIIlIl("CycBRdnKA5s=", "hpaeO");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[35]] = lIlIlllllIIIlII("GgQnTlieFUo=", "whRrx");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[36]] = lIlIlllllIIIIll("a3NM", "HPoVK");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[37]] = lIlIlllllIIIlIl("t5n0YXmK+84=", "sVOyB");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[5]] = lIlIlllllIIIlIl("vWxqFBHVnBg=", "uEyTD");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[38]] = lIlIlllllIIIlII("okcMtbvRmME=", "wcHac");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[39]] = lIlIlllllIIIlIl("ZngTHe9aZEI=", "HzUnX");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[40]] = lIlIlllllIIIlIl("1zv6OXy46Wo=", "SnTLo");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[43]] = lIlIlllllIIIIll("NjIf", "quXpH");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[44]] = lIlIlllllIIIIll("KDIo", "oaoBY");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[45]] = lIlIlllllIIIlIl("5lOva/f1AR0=", "zPlqm");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[48]] = lIlIlllllIIIlIl("ON9MLwx+AEg=", "vMbKE");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[49]] = lIlIlllllIIIlIl("uCU2y6HTY2c=", "KUasI");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[51]] = lIlIlllllIIIIll("Gzw=", "Xmeiq");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[7]] = lIlIlllllIIIIll("OxQ=", "jWvmt");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[54]] = lIlIlllllIIIlII("WYc+fEGW2xY=", "QDIca");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[55]] = lIlIlllllIIIlIl("1VZOwSo8AyI=", "vgCNK");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[57]] = lIlIlllllIIIIll("BSs=", "VxPRe");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[58]] = lIlIlllllIIIIll("Ox4=", "hMrDr");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[59]] = lIlIlllllIIIIll("Ohs=", "iHkLx");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[60]] = lIlIlllllIIIlIl("8kZ+l775avM=", "OXMxg");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[61]] = lIlIlllllIIIlIl("8P9znGTr1O4=", "qubbg");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[62]] = lIlIlllllIIIlII("tmSKyVaFN6U=", "nPlta");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[63]] = lIlIlllllIIIIll("FxI=", "DAtqh");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[64]] = lIlIlllllIIIlII("LEY31e/+tDY=", "fiomT");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[65]] = lIlIlllllIIIlIl("tWMObJlUVrc=", "KxHri");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[66]] = lIlIlllllIIIIll("NDoq", "giyWL");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[67]] = lIlIlllllIIIIll("Ax41", "PMfPa");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[68]] = lIlIlllllIIIlIl("D5jMkAACWdw=", "crhgl");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[69]] = lIlIlllllIIIlIl("+dMszSA1shc=", "ZBVnM");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[70]] = lIlIlllllIIIlIl("DLI6ZGC33M0=", "kvReK");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[72]] = lIlIlllllIIIlIl("vt7etyuGwYk=", "CSOll");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[73]] = lIlIlllllIIIlII("QTlRbRexBKE=", "BuMeF");
        RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[74]] = lIlIlllllIIIIll("HwYb", "LEHiT");
    }
    
    static {
        lIllIIIIIlIIlII();
        lIlIlllllIlIIlI();
    }
    
    private static boolean lIllIIIIIlIIlIl(final int lllllllllllllIlIlIlIIlllllIllIIl, final int lllllllllllllIlIlIlIIlllllIllIII) {
        return lllllllllllllIlIlIlIIlllllIllIIl < lllllllllllllIlIlIlIIlllllIllIII;
    }
    
    private static void lIllIIIIIlIIlII() {
        (llllllIlIlllI = new int[76])[0] = (0x12 ^ 0x17);
        RecipesCrafting.llllllIlIlllI[1] = ((0xC ^ 0x3C) & ~(0x55 ^ 0x65));
        RecipesCrafting.llllllIlIlllI[2] = " ".length();
        RecipesCrafting.llllllIlIlllI[3] = "  ".length();
        RecipesCrafting.llllllIlIlllI[4] = "   ".length();
        RecipesCrafting.llllllIlIlllI[5] = (0x2E ^ 0xD);
        RecipesCrafting.llllllIlIlllI[6] = (0x34 ^ 0x30);
        RecipesCrafting.llllllIlIlllI[7] = (0x2 ^ 0x1A ^ (0x84 ^ 0xB1));
        RecipesCrafting.llllllIlIlllI[8] = (0x37 ^ 0x30);
        RecipesCrafting.llllllIlIlllI[9] = (0x22 ^ 0x24);
        RecipesCrafting.llllllIlIlllI[10] = (0x61 ^ 0xB ^ (0x96 ^ 0xB9));
        RecipesCrafting.llllllIlIlllI[11] = (0x14 ^ 0x1C);
        RecipesCrafting.llllllIlIlllI[12] = (0x3C ^ 0x35 ^ ((0x4D ^ 0x1) & ~(0x65 ^ 0x29)));
        RecipesCrafting.llllllIlIlllI[13] = (0xC9 ^ 0xC3);
        RecipesCrafting.llllllIlIlllI[14] = (0xD ^ 0x6);
        RecipesCrafting.llllllIlIlllI[15] = (119 + 38 - 48 + 73 ^ 67 + 5 - 10 + 124);
        RecipesCrafting.llllllIlIlllI[16] = (0x55 ^ 0x4D ^ (0x1A ^ 0xF));
        RecipesCrafting.llllllIlIlllI[17] = (0x2D ^ 0x23);
        RecipesCrafting.llllllIlIlllI[18] = (0x99 ^ 0x96);
        RecipesCrafting.llllllIlIlllI[19] = (0x70 ^ 0xE ^ (0x6E ^ 0x0));
        RecipesCrafting.llllllIlIlllI[20] = (0x2D ^ 0xF ^ (0x85 ^ 0xB6));
        RecipesCrafting.llllllIlIlllI[21] = (73 + 79 - 111 + 116 ^ 105 + 116 - 84 + 6);
        RecipesCrafting.llllllIlIlllI[22] = (0x26 ^ 0x35);
        RecipesCrafting.llllllIlIlllI[23] = (28 + 130 - 82 + 66 ^ 77 + 153 - 80 + 4);
        RecipesCrafting.llllllIlIlllI[24] = (5 + 121 - 61 + 83 ^ 35 + 107 - 88 + 75);
        RecipesCrafting.llllllIlIlllI[25] = (0x43 ^ 0x55);
        RecipesCrafting.llllllIlIlllI[26] = (0x20 ^ 0x37);
        RecipesCrafting.llllllIlIlllI[27] = (0x7A ^ 0x62);
        RecipesCrafting.llllllIlIlllI[28] = (0x5D ^ 0x44);
        RecipesCrafting.llllllIlIlllI[29] = (0x7F ^ 0x3 ^ (0x6F ^ 0x9));
        RecipesCrafting.llllllIlIlllI[30] = (0x36 ^ 0x2D);
        RecipesCrafting.llllllIlIlllI[31] = (89 + 25 + 63 + 13 ^ 24 + 132 - 132 + 138);
        RecipesCrafting.llllllIlIlllI[32] = (0x12 ^ 0xF);
        RecipesCrafting.llllllIlIlllI[33] = (0x8F ^ 0xBD ^ (0xB ^ 0x27));
        RecipesCrafting.llllllIlIlllI[34] = (135 + 168 - 203 + 70 ^ 134 + 13 - 90 + 124);
        RecipesCrafting.llllllIlIlllI[35] = (0x8 ^ 0x28);
        RecipesCrafting.llllllIlIlllI[36] = (0x21 ^ 0x2E ^ (0x20 ^ 0xE));
        RecipesCrafting.llllllIlIlllI[37] = (0x40 ^ 0x37 ^ (0xE6 ^ 0xB3));
        RecipesCrafting.llllllIlIlllI[38] = (0xA2 ^ 0x86);
        RecipesCrafting.llllllIlIlllI[39] = (0x8A ^ 0xAF);
        RecipesCrafting.llllllIlIlllI[40] = (0xE1 ^ 0xC7);
        RecipesCrafting.llllllIlIlllI[41] = (0x90 ^ 0xC2);
        RecipesCrafting.llllllIlIlllI[42] = (0x3C ^ 0x22 ^ (0xE2 ^ 0xBB));
        RecipesCrafting.llllllIlIlllI[43] = (41 + 100 - 55 + 55 ^ 156 + 89 - 118 + 43);
        RecipesCrafting.llllllIlIlllI[44] = (0x83 ^ 0xC5 ^ (0xCA ^ 0xA4));
        RecipesCrafting.llllllIlIlllI[45] = (0xE8 ^ 0xC1);
        RecipesCrafting.llllllIlIlllI[46] = (0x33 ^ 0x5D ^ (0x3 ^ 0x3E));
        RecipesCrafting.llllllIlIlllI[47] = (0x36 ^ 0x79);
        RecipesCrafting.llllllIlIlllI[48] = (0x82 ^ 0x84 ^ (0xAC ^ 0x80));
        RecipesCrafting.llllllIlIlllI[49] = (0xAB ^ 0x80);
        RecipesCrafting.llllllIlIlllI[50] = (0x8D ^ 0xC3);
        RecipesCrafting.llllllIlIlllI[51] = (0x62 ^ 0x4E);
        RecipesCrafting.llllllIlIlllI[52] = (0xD8 ^ 0x9B);
        RecipesCrafting.llllllIlIlllI[53] = (0x3B ^ 0x71 ^ (0x6A ^ 0x71));
        RecipesCrafting.llllllIlIlllI[54] = (0x11 ^ 0x3F);
        RecipesCrafting.llllllIlIlllI[55] = (0x20 ^ 0x1A ^ (0xAD ^ 0xB8));
        RecipesCrafting.llllllIlIlllI[56] = (0xC5 ^ 0x8B ^ (0x3 ^ 0x9));
        RecipesCrafting.llllllIlIlllI[57] = (0x87 ^ 0xB7);
        RecipesCrafting.llllllIlIlllI[58] = (((0xE ^ 0x39) & ~(0x6F ^ 0x58)) ^ (0x41 ^ 0x70));
        RecipesCrafting.llllllIlIlllI[59] = (100 + 110 - 144 + 71 ^ 11 + 19 + 115 + 42);
        RecipesCrafting.llllllIlIlllI[60] = (0x14 ^ 0x27);
        RecipesCrafting.llllllIlIlllI[61] = (2 + 172 - 89 + 96 ^ 64 + 2 + 32 + 31);
        RecipesCrafting.llllllIlIlllI[62] = (0x92 ^ 0xA7);
        RecipesCrafting.llllllIlIlllI[63] = (0x9 ^ 0x3F);
        RecipesCrafting.llllllIlIlllI[64] = (0x7C ^ 0x4B);
        RecipesCrafting.llllllIlIlllI[65] = (0x9 ^ 0x4E ^ 89 + 36 - 44 + 46);
        RecipesCrafting.llllllIlIlllI[66] = (144 + 7 - 84 + 99 ^ 103 + 46 - 74 + 84);
        RecipesCrafting.llllllIlIlllI[67] = (0x48 ^ 0x72);
        RecipesCrafting.llllllIlIlllI[68] = (0x94 ^ 0x83 ^ (0x52 ^ 0x7E));
        RecipesCrafting.llllllIlIlllI[69] = (0x2D ^ 0x11);
        RecipesCrafting.llllllIlIlllI[70] = (0xD0 ^ 0x80 ^ (0xD1 ^ 0xBC));
        RecipesCrafting.llllllIlIlllI[71] = (102 + 127 - 96 + 97 ^ 105 + 143 - 137 + 64);
        RecipesCrafting.llllllIlIlllI[72] = (0x63 ^ 0x5D);
        RecipesCrafting.llllllIlIlllI[73] = (0xFC ^ 0xC3);
        RecipesCrafting.llllllIlIlllI[74] = (0xD4 ^ 0x94);
        RecipesCrafting.llllllIlIlllI[75] = (0xF4 ^ 0xB5);
    }
    
    private static String lIlIlllllIIIIll(String lllllllllllllIlIlIlIIlllllllIIIl, final String lllllllllllllIlIlIlIIlllllllIIII) {
        lllllllllllllIlIlIlIIlllllllIIIl = new String(Base64.getDecoder().decode(lllllllllllllIlIlIlIIlllllllIIIl.getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        final StringBuilder lllllllllllllIlIlIlIIlllllllIlII = new StringBuilder();
        final char[] lllllllllllllIlIlIlIIlllllllIIll = lllllllllllllIlIlIlIIlllllllIIII.toCharArray();
        int lllllllllllllIlIlIlIIlllllllIIlI = RecipesCrafting.llllllIlIlllI[1];
        final boolean lllllllllllllIlIlIlIIllllllIllII = (Object)lllllllllllllIlIlIlIIlllllllIIIl.toCharArray();
        final byte lllllllllllllIlIlIlIIllllllIlIll = (byte)lllllllllllllIlIlIlIIllllllIllII.length;
        float lllllllllllllIlIlIlIIllllllIlIlI = RecipesCrafting.llllllIlIlllI[1];
        while (lIllIIIIIlIIlIl((int)lllllllllllllIlIlIlIIllllllIlIlI, lllllllllllllIlIlIlIIllllllIlIll)) {
            final char lllllllllllllIlIlIlIIlllllllIlll = lllllllllllllIlIlIlIIllllllIllII[lllllllllllllIlIlIlIIllllllIlIlI];
            lllllllllllllIlIlIlIIlllllllIlII.append((char)(lllllllllllllIlIlIlIIlllllllIlll ^ lllllllllllllIlIlIlIIlllllllIIll[lllllllllllllIlIlIlIIlllllllIIlI % lllllllllllllIlIlIlIIlllllllIIll.length]));
            "".length();
            ++lllllllllllllIlIlIlIIlllllllIIlI;
            ++lllllllllllllIlIlIlIIllllllIlIlI;
            "".length();
            if ("   ".length() <= " ".length()) {
                return null;
            }
        }
        return String.valueOf(lllllllllllllIlIlIlIIlllllllIlII);
    }
    
    private static String lIlIlllllIIIlII(final String lllllllllllllIlIlIlIIlllllIlllll, final String lllllllllllllIlIlIlIIllllllIIIII) {
        try {
            final SecretKeySpec lllllllllllllIlIlIlIIllllllIIlII = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lllllllllllllIlIlIlIIllllllIIIII.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            final Cipher lllllllllllllIlIlIlIIllllllIIIll = Cipher.getInstance("Blowfish");
            lllllllllllllIlIlIlIIllllllIIIll.init(RecipesCrafting.llllllIlIlllI[3], lllllllllllllIlIlIlIIllllllIIlII);
            return new String(lllllllllllllIlIlIlIIllllllIIIll.doFinal(Base64.getDecoder().decode(lllllllllllllIlIlIlIIlllllIlllll.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lllllllllllllIlIlIlIIllllllIIIlI) {
            lllllllllllllIlIlIlIIllllllIIIlI.printStackTrace();
            return null;
        }
    }
    
    public void addRecipes(final CraftingManager lllllllllllllIlIlIlIlIIIIIIIlllI) {
        final ItemStack llllllllllllIlllllllIIlIIIlIllII = new ItemStack(Blocks.chest);
        final Object[] llllllllllllIlllllllIIlIIIllllIl = new Object[RecipesCrafting.llllllIlIlllI[0]];
        llllllllllllIlllllllIIlIIIllllIl[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[1]];
        llllllllllllIlllllllIIlIIIllllIl[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[2]];
        llllllllllllIlllllllIIlIIIllllIl[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[3]];
        llllllllllllIlllllllIIlIIIllllIl[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl[RecipesCrafting.llllllIlIlllI[6]] = Blocks.planks;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII, llllllllllllIlllllllIIlIIIllllIl);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII2 = new ItemStack(Blocks.trapped_chest);
        final Object[] llllllllllllIlllllllIIlIIIllllIl2 = new Object[RecipesCrafting.llllllIlIlllI[0]];
        llllllllllllIlllllllIIlIIIllllIl2[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[4]];
        llllllllllllIlllllllIIlIIIllllIl2[RecipesCrafting.llllllIlIlllI[2]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl2[RecipesCrafting.llllllIlIlllI[3]] = Blocks.chest;
        llllllllllllIlllllllIIlIIIllllIl2[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[7];
        llllllllllllIlllllllIIlIIIllllIl2[RecipesCrafting.llllllIlIlllI[6]] = Blocks.tripwire_hook;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII2, llllllllllllIlllllllIIlIIIllllIl2);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII3 = new ItemStack(Blocks.ender_chest);
        final Object[] llllllllllllIlllllllIIlIIIllllIl3 = new Object[RecipesCrafting.llllllIlIlllI[8]];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[0]];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[9]];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[6]] = Blocks.obsidian;
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[0]] = (char)RecipesCrafting.llllllIlIlllI[10];
        llllllllllllIlllllllIIlIIIllllIl3[RecipesCrafting.llllllIlIlllI[9]] = Items.ender_eye;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII3, llllllllllllIlllllllIIlIIIllllIl3);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII4 = new ItemStack(Blocks.furnace);
        final Object[] llllllllllllIlllllllIIlIIIllllIl4 = new Object[RecipesCrafting.llllllIlIlllI[0]];
        llllllllllllIlllllllIIlIIIllllIl4[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[8]];
        llllllllllllIlllllllIIlIIIllllIl4[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[11]];
        llllllllllllIlllllllIIlIIIllllIl4[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[12]];
        llllllllllllIlllllllIIlIIIllllIl4[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl4[RecipesCrafting.llllllIlIlllI[6]] = Blocks.cobblestone;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII4, llllllllllllIlllllllIIlIIIllllIl4);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII5 = new ItemStack(Blocks.crafting_table);
        final Object[] llllllllllllIlllllllIIlIIIllllIl5 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl5[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[13]];
        llllllllllllIlllllllIIlIIIllllIl5[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[14]];
        llllllllllllIlllllllIIlIIIllllIl5[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl5[RecipesCrafting.llllllIlIlllI[4]] = Blocks.planks;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII5, llllllllllllIlllllllIIlIIIllllIl5);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII6 = new ItemStack(Blocks.sandstone);
        final Object[] llllllllllllIlllllllIIlIIIllllIl6 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl6[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[15]];
        llllllllllllIlllllllIIlIIIllllIl6[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[16]];
        llllllllllllIlllllllIIlIIIllllIl6[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl6[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.sand, RecipesCrafting.llllllIlIlllI[2], BlockSand.EnumType.SAND.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII6, llllllllllllIlllllllIIlIIIllllIl6);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII7 = new ItemStack(Blocks.red_sandstone);
        final Object[] llllllllllllIlllllllIIlIIIllllIl7 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl7[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[17]];
        llllllllllllIlllllllIIlIIIllllIl7[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[18]];
        llllllllllllIlllllllIIlIIIllllIl7[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl7[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.sand, RecipesCrafting.llllllIlIlllI[2], BlockSand.EnumType.RED_SAND.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII7, llllllllllllIlllllllIIlIIIllllIl7);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII8 = new ItemStack(Blocks.sandstone, RecipesCrafting.llllllIlIlllI[6], BlockSandStone.EnumType.SMOOTH.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl8 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl8[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[19]];
        llllllllllllIlllllllIIlIIIllllIl8[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[20]];
        llllllllllllIlllllllIIlIIIllllIl8[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl8[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.sandstone, RecipesCrafting.llllllIlIlllI[2], BlockSandStone.EnumType.DEFAULT.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII8, llllllllllllIlllllllIIlIIIllllIl8);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII9 = new ItemStack(Blocks.red_sandstone, RecipesCrafting.llllllIlIlllI[6], BlockRedSandstone.EnumType.SMOOTH.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl9 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl9[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[21]];
        llllllllllllIlllllllIIlIIIllllIl9[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[22]];
        llllllllllllIlllllllIIlIIIllllIl9[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl9[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.red_sandstone, RecipesCrafting.llllllIlIlllI[2], BlockRedSandstone.EnumType.DEFAULT.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII9, llllllllllllIlllllllIIlIIIllllIl9);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII10 = new ItemStack(Blocks.sandstone, RecipesCrafting.llllllIlIlllI[2], BlockSandStone.EnumType.CHISELED.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl10 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl10[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[23]];
        llllllllllllIlllllllIIlIIIllllIl10[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[24]];
        llllllllllllIlllllllIIlIIIllllIl10[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl10[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone_slab, RecipesCrafting.llllllIlIlllI[2], BlockStoneSlab.EnumType.SAND.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII10, llllllllllllIlllllllIIlIIIllllIl10);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII11 = new ItemStack(Blocks.red_sandstone, RecipesCrafting.llllllIlIlllI[2], BlockRedSandstone.EnumType.CHISELED.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl11 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl11[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[25]];
        llllllllllllIlllllllIIlIIIllllIl11[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[26]];
        llllllllllllIlllllllIIlIIIllllIl11[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl11[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone_slab2, RecipesCrafting.llllllIlIlllI[2], BlockStoneSlabNew.EnumType.RED_SANDSTONE.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII11, llllllllllllIlllllllIIlIIIllllIl11);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII12 = new ItemStack(Blocks.quartz_block, RecipesCrafting.llllllIlIlllI[2], BlockQuartz.EnumType.CHISELED.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl12 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl12[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[27]];
        llllllllllllIlllllllIIlIIIllllIl12[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[28]];
        llllllllllllIlllllllIIlIIIllllIl12[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl12[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone_slab, RecipesCrafting.llllllIlIlllI[2], BlockStoneSlab.EnumType.QUARTZ.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII12, llllllllllllIlllllllIIlIIIllllIl12);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII13 = new ItemStack(Blocks.quartz_block, RecipesCrafting.llllllIlIlllI[3], BlockQuartz.EnumType.LINES_Y.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl13 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl13[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[29]];
        llllllllllllIlllllllIIlIIIllllIl13[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[30]];
        llllllllllllIlllllllIIlIIIllllIl13[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl13[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.quartz_block, RecipesCrafting.llllllIlIlllI[2], BlockQuartz.EnumType.DEFAULT.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII13, llllllllllllIlllllllIIlIIIllllIl13);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII14 = new ItemStack(Blocks.stonebrick, RecipesCrafting.llllllIlIlllI[6]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl14 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl14[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[31]];
        llllllllllllIlllllllIIlIIIllllIl14[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[32]];
        llllllllllllIlllllllIIlIIIllllIl14[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl14[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.STONE.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII14, llllllllllllIlllllllIIlIIIllllIl14);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII15 = new ItemStack(Blocks.stonebrick, RecipesCrafting.llllllIlIlllI[2], BlockStoneBrick.CHISELED_META);
        final Object[] llllllllllllIlllllllIIlIIIllllIl15 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl15[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[33]];
        llllllllllllIlllllllIIlIIIllllIl15[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[34]];
        llllllllllllIlllllllIIlIIIllllIl15[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl15[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone_slab, RecipesCrafting.llllllIlIlllI[2], BlockStoneSlab.EnumType.SMOOTHBRICK.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII15, llllllllllllIlllllllIIlIIIllllIl15);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIIllIIl = new ItemStack(Blocks.stonebrick, RecipesCrafting.llllllIlIlllI[2], BlockStoneBrick.MOSSY_META);
        final Object[] llllllllllllIlllllllIIlIIIIllIII = new Object[RecipesCrafting.llllllIlIlllI[3]];
        llllllllllllIlllllllIIlIIIIllIII[RecipesCrafting.llllllIlIlllI[1]] = Blocks.stonebrick;
        llllllllllllIlllllllIIlIIIIllIII[RecipesCrafting.llllllIlIlllI[2]] = Blocks.vine;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addShapelessRecipe(llllllllllllIlllllllIIlIIIIllIIl, llllllllllllIlllllllIIlIIIIllIII);
        final ItemStack llllllllllllIlllllllIIlIIIIllIIl2 = new ItemStack(Blocks.mossy_cobblestone, RecipesCrafting.llllllIlIlllI[2]);
        final Object[] llllllllllllIlllllllIIlIIIIllIII2 = new Object[RecipesCrafting.llllllIlIlllI[3]];
        llllllllllllIlllllllIIlIIIIllIII2[RecipesCrafting.llllllIlIlllI[1]] = Blocks.cobblestone;
        llllllllllllIlllllllIIlIIIIllIII2[RecipesCrafting.llllllIlIlllI[2]] = Blocks.vine;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addShapelessRecipe(llllllllllllIlllllllIIlIIIIllIIl2, llllllllllllIlllllllIIlIIIIllIII2);
        final ItemStack llllllllllllIlllllllIIlIIIlIllII16 = new ItemStack(Blocks.iron_bars, RecipesCrafting.llllllIlIlllI[19]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl16 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl16[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[35]];
        llllllllllllIlllllllIIlIIIllllIl16[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[36]];
        llllllllllllIlllllllIIlIIIllllIl16[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl16[RecipesCrafting.llllllIlIlllI[4]] = Items.iron_ingot;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII16, llllllllllllIlllllllIIlIIIllllIl16);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII17 = new ItemStack(Blocks.glass_pane, RecipesCrafting.llllllIlIlllI[19]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl17 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl17[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[37]];
        llllllllllllIlllllllIIlIIIllllIl17[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[5]];
        llllllllllllIlllllllIIlIIIllllIl17[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[5];
        llllllllllllIlllllllIIlIIIllllIl17[RecipesCrafting.llllllIlIlllI[4]] = Blocks.glass;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII17, llllllllllllIlllllllIIlIIIllllIl17);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII18 = new ItemStack(Blocks.redstone_lamp, RecipesCrafting.llllllIlIlllI[2]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl18 = new Object[RecipesCrafting.llllllIlIlllI[8]];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[38]];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[39]];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[40]];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[41];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[6]] = Items.redstone;
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[0]] = (char)RecipesCrafting.llllllIlIlllI[42];
        llllllllllllIlllllllIIlIIIllllIl18[RecipesCrafting.llllllIlIlllI[9]] = Blocks.glowstone;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII18, llllllllllllIlllllllIIlIIIllllIl18);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII19 = new ItemStack(Blocks.beacon, RecipesCrafting.llllllIlIlllI[2]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl19 = new Object[RecipesCrafting.llllllIlIlllI[12]];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[43]];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[44]];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[45]];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[42];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[6]] = Blocks.glass;
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[0]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[9]] = Items.nether_star;
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[8]] = (char)RecipesCrafting.llllllIlIlllI[47];
        llllllllllllIlllllllIIlIIIllllIl19[RecipesCrafting.llllllIlIlllI[11]] = Blocks.obsidian;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII19, llllllllllllIlllllllIIlIIIllllIl19);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII20 = new ItemStack(Blocks.nether_brick, RecipesCrafting.llllllIlIlllI[2]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl20 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl20[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[48]];
        llllllllllllIlllllllIIlIIIllllIl20[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[49]];
        llllllllllllIlllllllIIlIIIllllIl20[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[50];
        llllllllllllIlllllllIIlIIIllllIl20[RecipesCrafting.llllllIlIlllI[4]] = Items.netherbrick;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII20, llllllllllllIlllllllIIlIIIllllIl20);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII21 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[3], BlockStone.EnumType.DIORITE.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl21 = new Object[RecipesCrafting.llllllIlIlllI[9]];
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[51]];
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[7]];
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[52];
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[4]] = Blocks.cobblestone;
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[6]] = (char)RecipesCrafting.llllllIlIlllI[53];
        llllllllllllIlllllllIIlIIIllllIl21[RecipesCrafting.llllllIlIlllI[0]] = Items.quartz;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII21, llllllllllllIlllllllIIlIIIllllIl21);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIIllIIl3 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.GRANITE.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIIllIII3 = new Object[RecipesCrafting.llllllIlIlllI[3]];
        llllllllllllIlllllllIIlIIIIllIII3[RecipesCrafting.llllllIlIlllI[1]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.DIORITE.getMetadata());
        llllllllllllIlllllllIIlIIIIllIII3[RecipesCrafting.llllllIlIlllI[2]] = Items.quartz;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addShapelessRecipe(llllllllllllIlllllllIIlIIIIllIIl3, llllllllllllIlllllllIIlIIIIllIII3);
        final ItemStack llllllllllllIlllllllIIlIIIIllIIl4 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[3], BlockStone.EnumType.ANDESITE.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIIllIII4 = new Object[RecipesCrafting.llllllIlIlllI[3]];
        llllllllllllIlllllllIIlIIIIllIII4[RecipesCrafting.llllllIlIlllI[1]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.DIORITE.getMetadata());
        llllllllllllIlllllllIIlIIIIllIII4[RecipesCrafting.llllllIlIlllI[2]] = Blocks.cobblestone;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addShapelessRecipe(llllllllllllIlllllllIIlIIIIllIIl4, llllllllllllIlllllllIIlIIIIllIII4);
        final ItemStack llllllllllllIlllllllIIlIIIlIllII22 = new ItemStack(Blocks.dirt, RecipesCrafting.llllllIlIlllI[6], BlockDirt.DirtType.COARSE_DIRT.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl22 = new Object[RecipesCrafting.llllllIlIlllI[9]];
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[54]];
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[55]];
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[56];
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.dirt, RecipesCrafting.llllllIlIlllI[2], BlockDirt.DirtType.DIRT.getMetadata());
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[6]] = (char)RecipesCrafting.llllllIlIlllI[42];
        llllllllllllIlllllllIIlIIIllllIl22[RecipesCrafting.llllllIlIlllI[0]] = Blocks.gravel;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII22, llllllllllllIlllllllIIlIIIllllIl22);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII23 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[6], BlockStone.EnumType.DIORITE_SMOOTH.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl23 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl23[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[57]];
        llllllllllllIlllllllIIlIIIllllIl23[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[58]];
        llllllllllllIlllllllIIlIIIllllIl23[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl23[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.DIORITE.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII23, llllllllllllIlllllllIIlIIIllllIl23);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII24 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[6], BlockStone.EnumType.GRANITE_SMOOTH.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl24 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl24[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[59]];
        llllllllllllIlllllllIIlIIIllllIl24[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[60]];
        llllllllllllIlllllllIIlIIIllllIl24[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl24[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.GRANITE.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII24, llllllllllllIlllllllIIlIIIllllIl24);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII25 = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[6], BlockStone.EnumType.ANDESITE_SMOOTH.getMetadata());
        final Object[] llllllllllllIlllllllIIlIIIllllIl25 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl25[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[61]];
        llllllllllllIlllllllIIlIIIllllIl25[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[62]];
        llllllllllllIlllllllIIlIIIllllIl25[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl25[RecipesCrafting.llllllIlIlllI[4]] = new ItemStack(Blocks.stone, RecipesCrafting.llllllIlIlllI[2], BlockStone.EnumType.ANDESITE.getMetadata());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII25, llllllllllllIlllllllIIlIIIllllIl25);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII26 = new ItemStack(Blocks.prismarine, RecipesCrafting.llllllIlIlllI[2], BlockPrismarine.ROUGH_META);
        final Object[] llllllllllllIlllllllIIlIIIllllIl26 = new Object[RecipesCrafting.llllllIlIlllI[6]];
        llllllllllllIlllllllIIlIIIllllIl26[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[63]];
        llllllllllllIlllllllIIlIIIllllIl26[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[64]];
        llllllllllllIlllllllIIlIIIllllIl26[RecipesCrafting.llllllIlIlllI[3]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl26[RecipesCrafting.llllllIlIlllI[4]] = Items.prismarine_shard;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII26, llllllllllllIlllllllIIlIIIllllIl26);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII27 = new ItemStack(Blocks.prismarine, RecipesCrafting.llllllIlIlllI[2], BlockPrismarine.BRICKS_META);
        final Object[] llllllllllllIlllllllIIlIIIllllIl27 = new Object[RecipesCrafting.llllllIlIlllI[0]];
        llllllllllllIlllllllIIlIIIllllIl27[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[65]];
        llllllllllllIlllllllIIlIIIllllIl27[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[66]];
        llllllllllllIlllllllIIlIIIllllIl27[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[67]];
        llllllllllllIlllllllIIlIIIllllIl27[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl27[RecipesCrafting.llllllIlIlllI[6]] = Items.prismarine_shard;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII27, llllllllllllIlllllllIIlIIIllllIl27);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII28 = new ItemStack(Blocks.prismarine, RecipesCrafting.llllllIlIlllI[2], BlockPrismarine.DARK_META);
        final Object[] llllllllllllIlllllllIIlIIIllllIl28 = new Object[RecipesCrafting.llllllIlIlllI[8]];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[68]];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[69]];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[70]];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[6]] = Items.prismarine_shard;
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[0]] = (char)RecipesCrafting.llllllIlIlllI[71];
        llllllllllllIlllllllIIlIIIllllIl28[RecipesCrafting.llllllIlIlllI[9]] = new ItemStack(Items.dye, RecipesCrafting.llllllIlIlllI[2], EnumDyeColor.BLACK.getDyeDamage());
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII28, llllllllllllIlllllllIIlIIIllllIl28);
        "".length();
        final ItemStack llllllllllllIlllllllIIlIIIlIllII29 = new ItemStack(Blocks.sea_lantern, RecipesCrafting.llllllIlIlllI[2], RecipesCrafting.llllllIlIlllI[1]);
        final Object[] llllllllllllIlllllllIIlIIIllllIl29 = new Object[RecipesCrafting.llllllIlIlllI[8]];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[1]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[72]];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[2]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[73]];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[3]] = RecipesCrafting.llllllIIIIIIl[RecipesCrafting.llllllIlIlllI[74]];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[4]] = (char)RecipesCrafting.llllllIlIlllI[46];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[6]] = Items.prismarine_shard;
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[0]] = (char)RecipesCrafting.llllllIlIlllI[52];
        llllllllllllIlllllllIIlIIIllllIl29[RecipesCrafting.llllllIlIlllI[9]] = Items.prismarine_crystals;
        lllllllllllllIlIlIlIlIIIIIIIlllI.addRecipe(llllllllllllIlllllllIIlIIIlIllII29, llllllllllllIlllllllIIlIIIllllIl29);
        "".length();
    }
    
    private static String lIlIlllllIIIlIl(final String lllllllllllllIlIlIlIlIIIIIIIIllI, final String lllllllllllllIlIlIlIlIIIIIIIIIll) {
        try {
            final SecretKeySpec lllllllllllllIlIlIlIlIIIIIIIlIIl = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(lllllllllllllIlIlIlIlIIIIIIIIIll.getBytes(StandardCharsets.UTF_8)), RecipesCrafting.llllllIlIlllI[11]), "DES");
            final Cipher lllllllllllllIlIlIlIlIIIIIIIlIII = Cipher.getInstance("DES");
            lllllllllllllIlIlIlIlIIIIIIIlIII.init(RecipesCrafting.llllllIlIlllI[3], lllllllllllllIlIlIlIlIIIIIIIlIIl);
            return new String(lllllllllllllIlIlIlIlIIIIIIIlIII.doFinal(Base64.getDecoder().decode(lllllllllllllIlIlIlIlIIIIIIIIllI.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lllllllllllllIlIlIlIlIIIIIIIIlll) {
            lllllllllllllIlIlIlIlIIIIIIIIlll.printStackTrace();
            return null;
        }
    }
}
